# Generated by Django 5.0.4 on 2024-12-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
