# Generated by Django 5.0.4 on 2024-12-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeyapp', '0002_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='images/default-product.png', upload_to='products/'),
        ),
    ]
