# Generated by Django 5.0.4 on 2025-01-14 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeyapp', '0009_category_remove_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categri', to='honeyapp.category'),
            preserve_default=False,
        ),
    ]
